### PR TITLE
Floor serialization

### LINKED ISSUE #74: Add Custom Floor Adapter for Moshi Parsing.
We can parse the floor out of the gallery directly.
Objects have a gallery location which has floor in it.
Adding floor var with Int.MIN_VALUE might lead to confusion/bug if the floor is not assigned before it is accessed.

We could add the moshi adapter to convert floor string into the int in ArticGallery.
You could use it in ArticGallery.

```
/**
 * Parses floor as an integer. We default to [Int.MIN_VALUE] as 0 is a valid floor.
 */
class FloorAdapter {

    @ToJson
    fun toText(@Floor floor: Int): String = floor.toString()

    @FromJson
    @Floor
    fun fromText(text: String?): Int {
        return if (text != null) {
            try {
                return text.toInt()
            } catch (e: NumberFormatException) {
                if (text == "LL") {
                    0
                } else {
                    INVALID_FLOOR
                }
            }
        } else {
            INVALID_FLOOR
        }

    }
}

@Retention(AnnotationRetention.RUNTIME)
@JsonQualifier
annotation class Floor
then annotate the floor field in data class

        @Floor @Json(name = "audio_transcript")  val floor: Int

```

### PR DESCRIPTION
**Pull request by sam33rdhakal**
* resolves #74 
* converts string floor to int in gallery and tour

### CODE REVIEW

File: db/src/main/kotlin/edu/artic/db/Constants.kt [hunk 1]
```diff
@@ -0,0 +1,7 @@
+package edu.artic.db
+
+/**
+ * @author Sameer Dhakal (Fuzz)
+ */
+
+const val INVALID_FLOOR: Int = Int.MIN_VALUE
```
Comment (agrosner) [inline db/src/main/kotlin/edu/artic/db/Constants.kt]: oh wait please add doc here on what this is. `Constants.kt` is a little too vague.

File: db/src/main/kotlin/edu/artic/db/MoshiAdapters.kt [hunk 2]
```diff
@@ -63,4 +65,36 @@ class ZonedDateTimeAdapter {
 
     @FromJson
     fun fromText(text: String): ZonedDateTime = ZonedDateTime.parse(text, formatter)
-}
\ No newline at end of file
+}
+
+/**
+ * Parses floor as an integer. We default to [Int.MIN_VALUE] as 0 is a valid floor.
```
Comment (Cliabhach) [inline db/src/main/kotlin/edu/artic/db/MoshiAdapters.kt]: Update text since we now have an `INVALID_FLOOR` constant. Maybe just add a blank line, then `@see INVALID_FLOOR`.

File: db/src/main/kotlin/edu/artic/db/MoshiAdapters.kt [hunk 3]
```diff
@@ -63,4 +65,36 @@ class ZonedDateTimeAdapter {
...
+    fun toText(@Floor floor: Int): String = floor.toString()
+
+    @FromJson
+    @Floor
+    fun fromText(text: String?): Int {
+        return if (text != null) {
+            try {
+                return text.toInt()
+            } catch (e: NumberFormatException) {
+                if (text == "LL") {
```
Comment (Cliabhach) [inline db/src/main/kotlin/edu/artic/db/MoshiAdapters.kt]: Explicit comment above this line: `"LL" stands for 'Lower level'` or something like that.

File: db/src/main/kotlin/edu/artic/db/Constants.kt (hunk 1 above)
Comment (sam33rdhakal) [reply db/src/main/kotlin/edu/artic/db/Constants.kt]: Added.

File: db/src/main/kotlin/edu/artic/db/MoshiAdapters.kt (hunk 3 above)
Comment (sam33rdhakal) [reply db/src/main/kotlin/edu/artic/db/MoshiAdapters.kt]: Updated.

File: db/src/main/kotlin/edu/artic/db/MoshiAdapters.kt (hunk 2 above)
Comment (sam33rdhakal) [reply db/src/main/kotlin/edu/artic/db/MoshiAdapters.kt]: Modified the comment.
